### ISSUE TITLE
Fails to get gas tarriffs

### ISSUE THREAD

**Issue by rnlgreen** [ChristopherJohnston/octopus_energy#6]
There's a typo on line 90 of client.py where it sets the URL to fetch the gas tariff.  It is coded as "E-1R" but should read "G-1R".

**Comment by ChristopherJohnston** [comment]
Thanks. Feel free to submit a PR or I can fix over the coming days.

**Comment by ChristopherJohnston** [comment]
Released in [Minor Release 0.0.12](https://github.com/ChristopherJohnston/octopus_energy/actions/runs/2073583001)
